import "./globals.css";
import { Manrope } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${manrope.variable} font-mono`}
        style={{ backgroundColor: "#f7f7f7" }}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
